# Generated by Django 3.1.3 on 2021-03-20 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
