# Generated by Django 3.1.3 on 2021-03-23 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('SB', 'Sports Bike'), ('RB', 'Racing Bike')], default='RB', max_length=2),
        ),
        migrations.AlterField(
            model_name='image',
            name='img_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
