# Generated by Django 3.1.3 on 2021-03-23 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20210323_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('SB', 'Sports Bike'), ('RB', 'Road Bike')], default='RB', max_length=2),
        ),
    ]
