# Generated by Django 3.1.3 on 2021-03-24 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20210323_0300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='bike_id',
        ),
        migrations.AddField(
            model_name='image',
            name='bike_id',
            field=models.ManyToManyField(related_name='gallery', to='store.Product'),
        ),
    ]
