# Generated by Django 3.1.3 on 2021-03-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20210324_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_slug',
            field=models.SlugField(default=1, max_length=100),
        ),
    ]
