# Generated by Django 3.1.3 on 2021-04-03 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_auto_20210403_1623'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
