# Generated by Django 3.1.3 on 2021-04-04 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_order_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total',
            new_name='total_price',
        ),
    ]
