# Generated by Django 3.1.3 on 2021-04-04 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_auto_20210404_0641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.FloatField(default=True),
            preserve_default=False,
        ),
    ]
