# Generated by Django 3.1.3 on 2021-04-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_auto_20210409_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payer_id',
            field=models.CharField(default=True, max_length=200),
        ),
    ]
