# Generated by Django 3.1.3 on 2021-04-09 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_order_payer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Accepte', 'Accepted')], default='New', max_length=10),
        ),
    ]
